# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/2021-FPGA-System-Design/Lab2-Block Design and Debugger Set Up/lab2_vivado_proj/lab2_vivado_proj.srcs/sources_1/bd/design_1/ip/design_1_RGB_LED_0_0/design_1_RGB_LED_0_0.xci
# IP: The module: 'design_1_RGB_LED_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/2021-FPGA-System-Design/Lab2-Block Design and Debugger Set Up/lab2_vivado_proj/lab2_vivado_proj.gen/sources_1/bd/design_1/ip/design_1_RGB_LED_0_0/constrs_1/imports/xdc/RGB_LED_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_RGB_LED_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/2021-FPGA-System-Design/Lab2-Block Design and Debugger Set Up/lab2_vivado_proj/lab2_vivado_proj.srcs/sources_1/bd/design_1/ip/design_1_RGB_LED_0_0/design_1_RGB_LED_0_0.xci
# IP: The module: 'design_1_RGB_LED_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/2021-FPGA-System-Design/Lab2-Block Design and Debugger Set Up/lab2_vivado_proj/lab2_vivado_proj.gen/sources_1/bd/design_1/ip/design_1_RGB_LED_0_0/constrs_1/imports/xdc/RGB_LED_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_RGB_LED_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
