set_property SRC_FILE_INFO {cfile:D:/2021-FPGA-offline/Lab5-DSP_module/5-1_block_design/project_1/project_1.srcs/constrs_1/new/constraint.xdc rfile:../../../project_1.srcs/constrs_1/new/constraint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/axi_gpio_0_gpio_io_o[0]} {design_1_i/axi_gpio_0_gpio_io_o[1]} {design_1_i/axi_gpio_0_gpio_io_o[2]} {design_1_i/axi_gpio_0_gpio_io_o[3]} {design_1_i/axi_gpio_0_gpio_io_o[4]} {design_1_i/axi_gpio_0_gpio_io_o[5]} {design_1_i/axi_gpio_0_gpio_io_o[6]} {design_1_i/axi_gpio_0_gpio_io_o[7]} {design_1_i/axi_gpio_0_gpio_io_o[8]} {design_1_i/axi_gpio_0_gpio_io_o[9]} {design_1_i/axi_gpio_0_gpio_io_o[10]} {design_1_i/axi_gpio_0_gpio_io_o[11]} {design_1_i/axi_gpio_0_gpio_io_o[12]} {design_1_i/axi_gpio_0_gpio_io_o[13]} {design_1_i/axi_gpio_0_gpio_io_o[14]} {design_1_i/axi_gpio_0_gpio_io_o[15]} {design_1_i/axi_gpio_0_gpio_io_o[16]} {design_1_i/axi_gpio_0_gpio_io_o[17]} {design_1_i/axi_gpio_0_gpio_io_o[18]} {design_1_i/axi_gpio_0_gpio_io_o[19]} {design_1_i/axi_gpio_0_gpio_io_o[20]} {design_1_i/axi_gpio_0_gpio_io_o[21]} {design_1_i/axi_gpio_0_gpio_io_o[22]} {design_1_i/axi_gpio_0_gpio_io_o[23]} {design_1_i/axi_gpio_0_gpio_io_o[24]} {design_1_i/axi_gpio_0_gpio_io_o[25]} {design_1_i/axi_gpio_0_gpio_io_o[26]} {design_1_i/axi_gpio_0_gpio_io_o[27]} {design_1_i/axi_gpio_0_gpio_io_o[28]} {design_1_i/axi_gpio_0_gpio_io_o[29]} {design_1_i/axi_gpio_0_gpio_io_o[30]} {design_1_i/axi_gpio_0_gpio_io_o[31]}]]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/dsp_macro_0_P[0]} {design_1_i/dsp_macro_0_P[1]} {design_1_i/dsp_macro_0_P[2]} {design_1_i/dsp_macro_0_P[3]} {design_1_i/dsp_macro_0_P[4]} {design_1_i/dsp_macro_0_P[5]} {design_1_i/dsp_macro_0_P[6]} {design_1_i/dsp_macro_0_P[7]} {design_1_i/dsp_macro_0_P[8]} {design_1_i/dsp_macro_0_P[9]} {design_1_i/dsp_macro_0_P[10]} {design_1_i/dsp_macro_0_P[11]} {design_1_i/dsp_macro_0_P[12]} {design_1_i/dsp_macro_0_P[13]} {design_1_i/dsp_macro_0_P[14]} {design_1_i/dsp_macro_0_P[15]} {design_1_i/dsp_macro_0_P[16]} {design_1_i/dsp_macro_0_P[17]} {design_1_i/dsp_macro_0_P[18]} {design_1_i/dsp_macro_0_P[19]} {design_1_i/dsp_macro_0_P[20]} {design_1_i/dsp_macro_0_P[21]} {design_1_i/dsp_macro_0_P[22]} {design_1_i/dsp_macro_0_P[23]} {design_1_i/dsp_macro_0_P[24]} {design_1_i/dsp_macro_0_P[25]} {design_1_i/dsp_macro_0_P[26]} {design_1_i/dsp_macro_0_P[27]} {design_1_i/dsp_macro_0_P[28]} {design_1_i/dsp_macro_0_P[29]} {design_1_i/dsp_macro_0_P[30]} {design_1_i/dsp_macro_0_P[31]}]]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
